server {
    listen 5000;
    server_name _;
    root /usr/share/nginx/html;

    location = /index.html {
        add_header Cache-Control "no-store, no-cache";
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "public, max-age=3600";
        try_files $uri $uri/ /index.html;
    }
}
