version: "3"

tasks:
  run:
    desc: Run the app locally
    cmds:
      - npm run dev
    env:
      NODE_ENV: development
      DEBUG: "*,-babel"
      VITE_BACKEND_URL: https://tournament-sync-dev-48024539e01a.herokuapp.com
      VITE_FIREBASE_DATABASE: development
      PORT: 4000

  run-prod:
    desc: Run the ap as prod locally
    cmds:
      - npm run dev
    env:
      NODE_ENV: development
      DEBUG: "*,-babel"
      VITE_BACKEND_URL: https://tournament-sync-dev-48024539e01a.herokuapp.com
      VITE_FIREBASE_DATABASE: (default)
      PORT: 4000

  build:
    desc: Build the node app
    silent: true
    dir: .
    cmds:
      - npm run build

  test:
    desc: Test the node app
    dir: .
    cmds:
      - npm test

  help:
    desc: Display this help
    silent: true
    cmds:
      - task --list

  default:
    silent: true
    cmds:
      - task: help
