version: "3"

tasks:
  run:
    desc: Run the app locally
    cmds:
      - npm run dev
    env:
      NODE_ENV: development
      DEBUG: "*,-babel"
      VITE_BACKEND_URL: https://tournament-sync.herokuapp.com
      PORT: 4000

  run-prod:
    desc: Run the app locally
    cmds:
      - npm start
    env:
      NODE_ENV: production
      DEBUG: "*,-babel"
      PORT: 4000

  build:
    desc: Build the node app
    silent: true
    dir: .
    cmds:
      - npm run build

  test:
    desc: Test the node app
    dir: .
    cmds:
      - npm test

  help:
    desc: Display this help
    silent: true
    cmds:
      - task --list

  default:
    silent: true
    cmds:
      - task: help
